grafana: 
  image: grafana/grafana-oss:8.4.3 
  storage: 2Gi
heplifyServer: 
  image: sipcapture/heplify-server:latest
influxdb: 
  image: influxdb:1.8
  loglevel: info
  storage: 20Gi
homer: 
  image: sipcapture/webapp:latest
postgres: 
  image: postgres:11-alpine
  storage: 30Gi 
telegraf: 
  image: telegraf:1.19
jaeger: 
  image: jaegertracing/all-in-one:1.32

# Storage Class definition for the Stateful Sets
storageClassName:

# Affinity
affinity:
