# mysql configuration
mysql: 
  host: 
  database: jambones
  user: 
  storage: 10Gi
  secret: 
# redis configuration used by Node.js app that need to connect
redis: 
  host:  
  port: "6379"

# Storage Class definition for the StatefulSet
storageClassName:

# Affinity
affinity:
