{{- if .Values.apiban.apiKey }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: apiban-redis
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          {{- if .Values.global.affinity }}
          affinity:
            {{ toYaml .Values.global.affinity | default "" | nindent 12 }}
          {{- end }}
          containers:
          - name: apiban-redis
            image: jambonz/apiban-redis:latest
            imagePullPolicy: IfNotPresent
            env:
            - name: APIBAN_REDIS_KEY
              value: {{ .Values.apiban.redisKey | quote }}
            - name: APIBAN_REDIS_SERVER
              valueFrom:
                secretKeyRef:
                  name: jambonz-secrets
                  key: REDIS_HOST
            - name: APIBAN_REDIS_PORT
              value: {{ .Values.db.redis.port | quote }}
            - name: APIBAN_API_KEY
              value: {{ .Values.apiban.apiKey | quote }}
            - name: APIBAN_FOREVER_BLOCK_RANGES
              value: {{ .Values.apiban.foreverBlockRanges | quote }}
          restartPolicy: Never
{{- end }} 