apiVersion: v1
kind: Service
metadata:
  labels:
    app: sbc-sip-lb
{{ include "common.labels" . | indent 4 }}
  name: sbc-sip-lb
  namespace: {{ .Release.Namespace | quote }}
spec:
  ports:
    - name: sip-udp
      port: 5060
      targetPort: 5060
      protocol: UDP
  selector:
    app: jambonz-sbc-sip
  type: LoadBalancer
